---
driver:
  name: vagrant
  require_chef_omnibus: 12.5

provisioner:
  name: chef_solo
  test_repo_uri: https://github.com/dev-sec/tests-postgres-hardening.git

verifier:
  name: inspec
  sudo: true

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-6.8
- name: centos-7.2
- name: debian-7.11
- name: debian-8.6

suites:
- name: default-apt
  run_list:
  - recipe[apt]
  - recipe[postgresql::server]
  - recipe[postgres-hardening]
  excludes:
  - centos-6.8
  - centos-7.2
  - centos-7.11
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: '9.4'
      dir: '/etc/postgresql/9.4/main'
      password:
        postgres: 'iloverandompasswordsbutthiswilldo'
      server:
        service_name: 'postgresql'
        packages: [ 'postgresql-9.4' ]
      client:
        packages: [ 'postgresql-client-9.4', 'libpq-dev' ]
  verifier:
    inspec_tests:
      - https://github.com/dev-sec/postgres-baseline
- name: default-yum
  run_list:
  - recipe[apt]
  - recipe[postgresql::server]
  - recipe[postgres-hardening]
  excludes:
  - debian-7.11
  - debian-8.6
  - ubuntu-12.04
  - ubuntu-14.04
  - ubuntu-16.04
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: '9.4'
      server:
        packages: [ 'postgresql94-server' ]
        service_name: 'postgresql-9.4'
      client:
        packages: [ 'postgresql94', 'postgresql94-devel' ]
      setup_script: 'postgresql94-setup'
      password:
        postgres: 'iloverandompasswordsbutthiswilldo'
  verifier:
    inspec_tests:
      - https://github.com/dev-sec/postgres-baseline
