---
driver:
  name: vagrant
provisioner:
  name: chef_solo
  test_repo_uri: https://github.com/TelekomLabs/tests-postgres-hardening.git
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
- name: oracle-6.4
  driver_config:
    box: oracle-6.4
    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel64-64.box
- name: oracle-6.5
  driver_config:
    box: oracle-6.5
    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel65-64.box
- name: debian-6
  driver_config:
    box: debian-6
    box_url: https://s3.eu-central-1.amazonaws.com/ffuenf-vagrantboxes/debian/debian-6.0.10-amd64_virtualbox.box
- name: debian-7
  driver_config:
    box: debian-7
    box_url: https://s3.eu-central-1.amazonaws.com/ffuenf-vagrantboxes/debian/debian-7.7.0-amd64_virtualbox.box
suites:
- name: default
  run_list:
  - recipe[chef-solo-search]
  - recipe[apt]
  - recipe[postgresql::server]
  - recipe[postgres-hardening]
  excludes:
  - centos-6.4
  - centos-6.5
  - oracle-6.4
  - oracle-6.5
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: '9.3'
      password:
        postgres: iloverandompasswordsbutthiswilldo
- name: default-rhel
  run_list:
  - recipe[chef-solo-search]
  - recipe[apt]
  - recipe[postgresql::server]
  - recipe[postgres-hardening]
  excludes:
  - debian-6
  - debian-7
  - ubuntu-12.04
  - ubuntu-14.04
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: '9.3'
      password:
        postgres: iloverandompasswordsbutthiswilldo
