---
driver:
  name: vagrant
  require_chef_omnibus: 12.5
provisioner:
  name: chef_solo
  test_repo_uri: https://github.com/dev-sec/tests-postgres-hardening.git
platforms:
- name: ubuntu-12.04
  driver_config:
    box: ubuntu/precise64
    box_url: https://atlas.hashicorp.com/ubuntu/boxes/precise64/versions/20160627.0.0/providers/virtualbox.box
- name: ubuntu-14.04
  driver_config:
    box: ubuntu/trusty64
    box_url: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160627.0.0/providers/virtualbox.box
- name: ubuntu-16.04
  driver_config:
    box: ubuntu/xenial64
    box_url: https://atlas.hashicorp.com/ubuntu/boxes/xenial64/versions/20160627.0.0/providers/virtualbox.box
- name: centos-6.7
  driver_config:
    box: opscode-centos-6.7
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.7_chef-provisionerless.box
- name: centos-7.2
  driver_config:
    box: opscode-centos-7.2
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box
- name: oracle-6.4
  driver_config:
    box: oracle-6.4
    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel64-64.box
- name: oracle-6.5
  driver_config:
    box: oracle-6.5
    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel65-64.box
- name: debian-7
  driver_config:
    box: debian/wheezy64
    box_url: https://atlas.hashicorp.com/debian/boxes/wheezy64/versions/7.11.1/providers/virtualbox.box
- name: debian-8
  driver_config:
    box: debian/jessie64
    box_url: https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.5.1/providers/virtualbox.box

suites:
- name: default
  run_list:
  - recipe[chef-solo-search]
  - recipe[apt]
  - recipe[postgresql::server]
  - recipe[postgres-hardening]
  excludes:
  - centos-6.7
  - centos-7.2
  - oracle-6.4
  - oracle-6.5
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: '9.4'
      dir: '/etc/postgresql/9.4/main'
      password:
        postgres: 'iloverandompasswordsbutthiswilldo'
      server:
        service_name: 'postgresql'
        packages: [ 'postgresql-9.4' ]
      client:
        packages: [ 'postgresql-client-9.4', 'libpq-dev' ]
- name: default-rhel
  run_list:
  - recipe[chef-solo-search]
  - recipe[apt]
  - recipe[postgresql::server]
  - recipe[postgres-hardening]
  excludes:
  - debian-7
  - debian-8
  - ubuntu-12.04
  - ubuntu-14.04
  - ubuntu-16.04
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: '9.4'
      server:
        packages: [ 'postgresql94-server' ]
        service_name: 'postgresql-9.4'
      client:
        packages: [ 'postgresql94', 'postgresql94-devel' ]
      setup_script: 'postgresql94-setup'
      password:
        postgres: 'iloverandompasswordsbutthiswilldo'
