---
AllCops:
  DisplayCopNames: true
  Exclude:
  - vendor/**/*
  - test/**/*
Metrics/AbcSize:
  Max: 29
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/PerceivedComplexity:
  Max: 10
Style/Documentation:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: trailing
  Enabled: true
Style/Encoding:
  EnforcedStyle: always
  Enabled: true
Style/ExtraSpacing:
  Exclude:
    - attributes/default.rb
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/SpaceAroundOperators:
  Exclude:
    - attributes/default.rb
