---
sudo: required
language: ruby
cache: bundler
dist: trusty

services:
- docker

before_install:
- gem --version
- bundle version

matrix:
  include:
  # verify lint and unit
  - rvm: 2.3.3
    gemfile: Gemfile
    bundler_args: "--without integration guard tools"
  # integration tests
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='centos-6.7'
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='centos-7'
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='oracle-6.7'
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='oracle-7'
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='ubuntu-12.04'
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='ubuntu-14.04'
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='ubuntu-16.04'
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='debian-7'
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='debian-8'
  allow-failures:
  - env: SUITE=test:integration OS='fedora-24'
  - env: SUITE=test:integration OS='fedora-23'
